http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
  routers:
    dashboard:
      rule: "Host(`traefik.localhost`)"
      service: api@internal
      entryPoints:
        - web
